services:
  backend-service:
    image: ghcr.io/nikelaz/bw-backend-service:${BRANCH_TAG}
    restart: always
    depends_on:
      - database
    env_file: .env
    environment:
      - PORT=$BE_SERVICE_PORT
      - PG_HOST=database
      - PG_PORT=$PG_PORT
      - PG_USER=$PG_USER
      - PG_PASS=$PG_PASS 
      - PG_DB=$PG_DB
      - JWT_SECRET=$JWT_SECRET
    ports:
      - "${BE_SERVICE_PORT}:${BE_SERVICE_PORT}"
    volumes:
      - bw-backend-data:/usr/app/data   # persist app data if needed
    networks:
      - shared-network
    command: node ./dist/index.js

  web-client:
    image: ghcr.io/nikelaz/bw-web-client:${BRANCH_TAG}
    restart: always
    env_file: .env
    environment:
      - PORT=$WEB_CLIENT_PORT
    ports:
      - "${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}"
    volumes:
      - bw-client-data:/usr/app/data  # persist any client data if needed
    networks:
      - shared-network
    command: npm run start

  database:
    image: postgres:17
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: $PG_USER 
      POSTGRES_PASSWORD: $PG_PASS
      POSTGRES_DB: $PG_DB
    ports:
      - $PG_PORT:$PG_PORT
    volumes:
       - dbdata:/var/lib/postgresql/data
    networks:
      - shared-network
    command: -p $PG_PORT

networks:
  shared-network:
    driver: bridge

volumes:
  dbdata: {}
  bw-backend-data: {}
  bw-client-data: {}
