services:
  backend-service:
    build:
      context: packages/bw-backend-service
      dockerfile: Dockerfile.prod
    restart: always
    depends_on:
      - database
    env_file: .env
    environment:
      - PORT=$BE_SERVICE_PORT
      - PG_HOST=database
      - PG_PORT=$PG_PORT
      - PG_USER=$PG_USER
      - PG_PASS=$PG_PASS 
      - PG_DB=$PG_DB
      - JWT_SECRET=$JWT_SECRET
    ports:
      - ${BE_SERVICE_PORT}:${BE_SERVICE_PORT}
    volumes:
      - ./packages/bw-backend-service:/usr/app/
      - /usr/app/node_modules
    networks:
      - shared-network
    command: node ./dist/index.js

  web-client:
    build:
      context: packages/bw-web-client
      dockerfile: Dockerfile.prod
    restart: always
    env_file: .env
    environment:
      - PORT=$WEB_CLIENT_PORT
    ports:
      - ${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}
    volumes:
      - ./packages/bw-web-client:/usr/app/
      - /usr/app/node_modules
    networks:
      - shared-network
    command: npm run start

  database:
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: $PG_USER 
      POSTGRES_PASSWORD: $PG_PASS
      POSTGRES_DB: $PG_DB
    ports:
      - $PG_PORT:$PG_PORT
    volumes:
       - dbdata:/var/lib/postgresql/data
    networks:
      - shared-network
    command: -p $PG_PORT

networks:
  shared-network:
    driver: bridge

volumes:
  dbdata:
