name: Deployment Pipeline
on: [workflow_dispatch]
jobs:
  staging:
    name: Staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: remote into the ssh production server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/bw-monorepo-stage
          git stash
          git branch
          git checkout staging
          echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker compose down 
          git pull origin staging --rebase --recurse-submodules
          echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker compose -f docker-compose.prod.yml build --no-cache
          echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker compose -f docker-compose.prod.yml up -d 
          git stash pop
  production:
    name: Production
    runs-on: ubuntu-latest
    environment: production
    needs: Staging
    steps:
    - name: remote into the ssh production server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/bw-monorepo
          git stash
          git branch
          git checkout main
          echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker compose down 
          git pull origin main --rebase --recurse-submodules
          echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker compose -f docker-compose.prod.yml build --no-cache
          echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker compose -f docker-compose.prod.yml up -d 
          git stash pop
